language: node_js
services:
  - xvfb
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      - secure: RUrvPg4n4BhDRIjmixs/lD5uKzuP8Kxf9Pm6OvLRpNCCLb3+mbrqcmuLNkYx39EqndkN79uxu4MBkIRRIsh53GpoOOnRmnOJZvFlXi7u8zYG3iSAqIJOuquB9bH4ScqCX1AAdfcuQgpb/rP8fmWoUsJ8h2Yce6KEVC5rbx1OhrHBgCUvLWqC2h6ZO5vuQjOfaeXx+CpDzvkZfREzQTNVp6rvEVU7sNjqoBOfo/iZW6KqJalBmexSxbkHZ3d3d+adjjUNNP8PECLvopqv6p6XzztrUZedXzWiq+fO2HEl4zZwru5IhDgT4wQuJ0I0lmMwEZLCB7RGGqhyQ82j9X+rT/VUxbHf3cGL+ewsgaYv4lhuo5MG2BWm423YGX4N0gWkwBOiHMkunBml2qFO0lTKBU5IEjE+ZnDsgY6yBbJy5dKgfxwojysDuAkFHq2589/4np4u2UXAAty0rENLLqJjX4Tzi5Sk0bj814pY59zuaBsv1aIDQ27PHhW5LQdNR4vIFCIUeYJGUK6oXmejLRC9n69iJ4qNmHfLAmQZJ7QCJa9qMCATfxJKFEPVwF4/wplSoNESfD4otPJnZZjxkXu15uLNgi6dI2GzrCjG0S/w094IQ8aAm8jnsUb4jMIrREJzzRFRM0Lwx8kgih96S/8RAD2YCMrsGUaOYnIsH9kGEws=
